
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package minic_compis;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CORCHETES = 41;
  public static final int DOSPUNTOS = 61;
  public static final int CORCHETECLOSE = 55;
  public static final int DISTINTO = 40;
  public static final int DOBLEIGUAL = 39;
  public static final int READLINE = 23;
  public static final int MULT = 30;
  public static final int GUIONBAJO = 62;
  public static final int PUNTOYCOMA = 59;
  public static final int doubleConstant = 64;
  public static final int DOUBLE = 4;
  public static final int RESTA = 29;
  public static final int PARENTESIS = 43;
  public static final int PCLOSE = 51;
  public static final int INTERFACE = 8;
  public static final int INT = 3;
  public static final int intConstant = 63;
  public static final int FOR = 13;
  public static final int CORCHETEOPEN = 54;
  public static final int MENORIGUAL = 38;
  public static final int IDENTIFICADOR = 27;
  public static final int READINTEGER = 22;
  public static final int IGUAL = 33;
  public static final int OR = 36;
  public static final int BOOL = 5;
  public static final int ARROBA = 46;
  public static final int CLASS = 7;
  public static final int boolConstant = 65;
  public static final int NEWARRAY = 20;
  public static final int SUMA = 28;
  public static final int QUESTIONOPEN = 52;
  public static final int IF = 15;
  public static final int THIS = 10;
  public static final int GETBYTE = 25;
  public static final int MAYORIGUAL = 37;
  public static final int SETBYTE = 26;
  public static final int EOF = 0;
  public static final int RETURN = 17;
  public static final int NEW = 19;
  public static final int error = 1;
  public static final int COMA = 58;
  public static final int CADENA = 66;
  public static final int NULL = 9;
  public static final int MENOR = 34;
  public static final int MOD = 32;
  public static final int hexConstant = 67;
  public static final int BREAK = 18;
  public static final int VOID = 2;
  public static final int MAYOR = 35;
  public static final int AMPERSAN = 49;
  public static final int EXCLACLOSE = 45;
  public static final int SHARP = 47;
  public static final int ELSE = 16;
  public static final int PUNTO = 60;
  public static final int EXCLAOPEN = 44;
  public static final int LLAVES = 42;
  public static final int WHILE = 14;
  public static final int QUESTIONCLOSE = 53;
  public static final int DOLLAR = 48;
  public static final int LLAVEOPEN = 56;
  public static final int EXTENDS = 11;
  public static final int STRING = 6;
  public static final int MALLOC = 24;
  public static final int DIVISION = 31;
  public static final int POPEN = 50;
  public static final int IMPLEMENTS = 12;
  public static final int LLAVECLOSE = 57;
  public static final int PRINT = 21;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "VOID",
  "INT",
  "DOUBLE",
  "BOOL",
  "STRING",
  "CLASS",
  "INTERFACE",
  "NULL",
  "THIS",
  "EXTENDS",
  "IMPLEMENTS",
  "FOR",
  "WHILE",
  "IF",
  "ELSE",
  "RETURN",
  "BREAK",
  "NEW",
  "NEWARRAY",
  "PRINT",
  "READINTEGER",
  "READLINE",
  "MALLOC",
  "GETBYTE",
  "SETBYTE",
  "IDENTIFICADOR",
  "SUMA",
  "RESTA",
  "MULT",
  "DIVISION",
  "MOD",
  "IGUAL",
  "MENOR",
  "MAYOR",
  "OR",
  "MAYORIGUAL",
  "MENORIGUAL",
  "DOBLEIGUAL",
  "DISTINTO",
  "CORCHETES",
  "LLAVES",
  "PARENTESIS",
  "EXCLAOPEN",
  "EXCLACLOSE",
  "ARROBA",
  "SHARP",
  "DOLLAR",
  "AMPERSAN",
  "POPEN",
  "PCLOSE",
  "QUESTIONOPEN",
  "QUESTIONCLOSE",
  "CORCHETEOPEN",
  "CORCHETECLOSE",
  "LLAVEOPEN",
  "LLAVECLOSE",
  "COMA",
  "PUNTOYCOMA",
  "PUNTO",
  "DOSPUNTOS",
  "GUIONBAJO",
  "intConstant",
  "doubleConstant",
  "boolConstant",
  "CADENA",
  "hexConstant"
  };
}

