
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Dec 05 18:28:36 CST 2018
//----------------------------------------------------

package minic_compis;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CORCHETES = 52;
  public static final int DISTINTO = 39;
  public static final int READLINE = 23;
  public static final int PUNTOYCOMA = 43;
  public static final int PERIOD = 45;
  public static final int doubleConstant = 58;
  public static final int PARCERRADO = 49;
  public static final int DOUBLE = 4;
  public static final int RESTA = 29;
  public static final int PARENTESIS = 53;
  public static final int EXCLAM = 42;
  public static final int INTERFACE = 8;
  public static final int INT = 3;
  public static final int intConstant = 57;
  public static final int FOR = 13;
  public static final int stringConstant = 60;
  public static final int IDENTIFICADOR = 25;
  public static final int MENORIGUAL = 34;
  public static final int IGUAL = 37;
  public static final int READINTEGER = 22;
  public static final int OR = 41;
  public static final int BOOL = 5;
  public static final int LLAVABIERTA = 50;
  public static final int CLASS = 7;
  public static final int DIV = 31;
  public static final int boolConstant = 59;
  public static final int NEWARRAY = 20;
  public static final int SUMA = 28;
  public static final int CORCERRADO = 47;
  public static final int IF = 15;
  public static final int THIS = 10;
  public static final int GETBYTE = 26;
  public static final int MAYORIGUAL = 36;
  public static final int SETBYTE = 27;
  public static final int EOF = 0;
  public static final int RETURN = 17;
  public static final int NEW = 19;
  public static final int error = 1;
  public static final int COMA = 44;
  public static final int PARABIERTO = 48;
  public static final int NULL = 9;
  public static final int MENOR = 33;
  public static final int MOD = 32;
  public static final int hexConstant = 61;
  public static final int CONSTANT = 55;
  public static final int BREAK = 18;
  public static final int VOID = 2;
  public static final int MAYOR = 35;
  public static final int AMPERSONS = 40;
  public static final int ELSE = 16;
  public static final int PUNTO = 56;
  public static final int LLAVES = 54;
  public static final int WHILE = 14;
  public static final int CORABIERTO = 46;
  public static final int EXTENDS = 11;
  public static final int MULTI = 30;
  public static final int STRING = 6;
  public static final int MALLOC = 24;
  public static final int IGUALCOMPARACION = 38;
  public static final int IMPLEMENTS = 12;
  public static final int PRINT = 21;
  public static final int LLAVCERRADA = 51;
}

